# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edge_load_model <- function(model_path, n_ctx = 2048L, n_gpu_layers = 0L) {
    .Call(`_edgemodelr_edge_load_model`, model_path, n_ctx, n_gpu_layers)
}

edge_completion <- function(model_ptr, prompt, n_predict = 128L, temperature = 0.8, top_p = 0.95) {
    .Call(`_edgemodelr_edge_completion`, model_ptr, prompt, n_predict, temperature, top_p)
}

edge_free_model <- function(model_ptr) {
    invisible(.Call(`_edgemodelr_edge_free_model`, model_ptr))
}

is_valid_model <- function(model_ptr) {
    .Call(`_edgemodelr_is_valid_model`, model_ptr)
}

