# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.2.1']

    steps:
      - uses: actions/checkout@v4
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: R Package CRAN Submission
        # You may pin to the exact commit or the version.
        # uses: coatless-actions/cran-submission@0224a35fffe0afcac8392b2520d966537866da83
        uses: coatless-actions/cran-submission@v1
        with:
          # Directory containing the R package
          pkg-directory: # optional, default is .
          # Directory for check outputs
          check-directory: # optional, default is check
          # Stop on warnings or errors ("warning" or "error")
          error-on: # optional, default is warning
          # Whether to upload snapshots of failing tests
          upload-snapshots: # optional, default is true
          # Create a GitHub issue for the submission
          create-issue: # optional, default is true
          # R version to use
          r-version: # optional, default is release
          # Confirmation string to verify intent (e.g., "CONFIRM")
          confirmation: # optional, default is 
                
